#Word Embedding

In [30]:
from tensorflow.keras.preprocessing.text import one_hot

In [31]:
## sentences
sent=[
'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy' ,
'I am a good developer',
'understand the meaning of words' ,
'your videos are good',]

In [32]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [33]:
vocb_size = 10000
sent = [one_hot(word,vocb_size) for word in sent]
sent

[[7293, 8297, 8804, 1422],
 [7293, 8297, 8804, 5639],
 [7293, 4527, 8804, 6771],
 [756, 7351, 6150, 8927, 7331],
 [756, 7351, 6150, 8927, 4698],
 [2981, 7293, 2822, 8804, 8992],
 [6100, 818, 6354, 8927]]

In [34]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
sent_length = 8
embedded_docs = pad_sequences(sent,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7293 8297 8804 1422]
 [   0    0    0    0 7293 8297 8804 5639]
 [   0    0    0    0 7293 4527 8804 6771]
 [   0    0    0  756 7351 6150 8927 7331]
 [   0    0    0  756 7351 6150 8927 4698]
 [   0    0    0 2981 7293 2822 8804 8992]
 [   0    0    0    0 6100  818 6354 8927]]


In [36]:
dim = 10
model = Sequential()
model.add(Embedding(vocb_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [37]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step


array([[[-0.0329224 , -0.0096127 , -0.00335013, -0.03202415,
          0.01255267, -0.04525609, -0.02424885, -0.00474193,
          0.03379228, -0.00416623],
        [-0.0329224 , -0.0096127 , -0.00335013, -0.03202415,
          0.01255267, -0.04525609, -0.02424885, -0.00474193,
          0.03379228, -0.00416623],
        [-0.0329224 , -0.0096127 , -0.00335013, -0.03202415,
          0.01255267, -0.04525609, -0.02424885, -0.00474193,
          0.03379228, -0.00416623],
        [-0.0329224 , -0.0096127 , -0.00335013, -0.03202415,
          0.01255267, -0.04525609, -0.02424885, -0.00474193,
          0.03379228, -0.00416623],
        [ 0.00302889, -0.01771144, -0.04972101, -0.03634746,
         -0.03124657, -0.01170449, -0.00798689,  0.0054485 ,
          0.00793977, -0.00928692],
        [ 0.02334387,  0.01067089, -0.0029586 , -0.00597889,
         -0.01317233, -0.01528568, -0.01002904,  0.00710005,
         -0.02594225,  0.02840681],
        [ 0.01397795,  0.04855538, -0.0375527 , -0.0

#Preprocessing IMDB dataset for RNN

In [39]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [40]:
max_features = 10000
maxlen = 500
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

In [41]:
X_train.shape

(25000,)

In [42]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [43]:
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)

In [44]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

#Training simple RNN with Embedding layer

In [45]:
model = Sequential()
model.add(Embedding(max_features, 128,input_length = maxlen))
model.add(SimpleRNN(128,activation = 'relu'))
model.add(Dense(1, activation='sigmoid'))

In [46]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_1 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [48]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [49]:
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 134s 211ms/step - accuracy: 0.5561 - loss: 2933.7583 - val_accuracy: 0.6092 - val_loss: 0.6447
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 144s 215ms/step - accuracy: 0.6895 - loss: 0.6194 - val_accuracy: 0.6700 - val_loss: 0.6019
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 140s 213ms/step - accuracy: 0.7631 - loss: 0.5386 - val_accuracy: 0.6828 - val_loss: 0.5792
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 141s 211ms/step - accuracy: 0.8119 - loss: 0.4472 - val_accuracy: 0.7792 - val_loss: 0.4772
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 142s 211ms/step - accuracy: 0.8721 - loss: 0.3046 - val_accuracy: 0.7782 - val_loss: 0.4876
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 134s 214ms/step - accuracy: 0.9104 - loss: 0.2271 - val_accuracy: 0.7794 - val_loss: 0.5444
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 135s 216ms/step - accuracy: 0.9271 - loss: 0.1937 - val_accuracy: 0.7676 - val_loss: 0.5816
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 140s 212ms/step - accuracy: 0.954

In [50]:
model.save('simple_rnn_model.h5')

In [51]:
model.get_weights()

[array([[ 0.28639767,  0.2954545 , -0.30206943, ...,  0.26390678,
          0.20502765,  0.31957898],
        [-0.01205816, -0.02400729, -0.06486873, ...,  0.03969558,
         -0.02330582,  0.0351617 ],
        [ 0.02283679,  0.04764387, -0.07007543, ..., -0.0048192 ,
          0.05374426,  0.03179323],
        ...,
        [-0.04770818,  0.01622578, -0.03787387, ...,  0.02506675,
         -0.0159865 ,  0.02180779],
        [ 0.04435509,  0.02047168, -0.06695636, ...,  0.03038548,
          0.04070528,  0.06175116],
        [-0.03236922, -0.1292332 , -0.03605423, ..., -0.07640179,
          0.06672928,  0.13664825]], dtype=float32),
 array([[ 0.1234207 ,  0.06377999, -0.09195408, ...,  0.11165745,
         -0.14778574,  0.11026123],
        [ 0.12139811, -0.08596477, -0.11520311, ...,  0.10577945,
         -0.03173837, -0.12810639],
        [-0.11032465, -0.02838289,  0.02034536, ...,  0.16284284,
          0.05612471, -0.14701025],
        ...,
        [ 0.08052175,  0.03898626, -0.0

#Prediction

In [52]:
word_index = imdb.get_word_index()
reverse_word_index = {value:key for key,value in word_index.items()}

In [53]:
def decode_review(text):
    return ' '.join([reverse_word_index.get(i-3,'?') for i in text])

def preprocess_text(text):
  words = text.lower().split()
  encoded_review = [word_index.get(word,2) + 3 for word in words]
  padded_review = sequence.pad_sequences([encoded_review], maxlen=maxlen)
  return padded_review

In [54]:
def predict_sentiment(text):
  padded_review = preprocess_text(text)
  prediction = model.predict(padded_review)[0][0]
  sentiment = 'positive' if prediction > 0.5 else 'negative'
  return sentiment, prediction

In [65]:
text = "A visual treat with a strong story & characters A unique genre, a well written story (script) & strong characters give this movie a strong start."
sentiment, prediction = predict_sentiment(text)
sentiment, prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


('positive', 0.500694)